"""
Social Feed Monitor - Twitter & Google Reviews Pipeline

Monitors social media feeds and reviews for a target company, stores them
in JSON files accessible to the agent, and generates daily market analysis
reports via a heartbeat scheduler.

This demonstrates a practical data pipeline that a small business owner
can understand: watch what people say about you online, store it, and
get a daily summary of market sentiment.

For the hackathon demo, we use realistic sample data for Accelerate Okanagan.
In production, this would connect to the Twitter/X API and Google Places API.
"""

import asyncio
import json
import logging
import random
from dataclasses import dataclass, field, asdict
from datetime import datetime, timedelta
from pathlib import Path
from typing import Any, Optional

logger = logging.getLogger("tojo.social_feeds")

# ---------------------------------------------------------------------------
# Storage paths
# ---------------------------------------------------------------------------
FEEDS_DIR = Path.home() / ".tojo" / "social_feeds"
TWITTER_FILE = FEEDS_DIR / "twitter_feed.json"
REVIEWS_FILE = FEEDS_DIR / "google_reviews.json"
REPORTS_DIR = FEEDS_DIR / "reports"


# ---------------------------------------------------------------------------
# Data models
# ---------------------------------------------------------------------------

@dataclass
class Tweet:
    """A single tweet/post about the target company."""
    id: str
    author: str
    handle: str
    content: str
    timestamp: str
    likes: int = 0
    retweets: int = 0
    replies: int = 0
    sentiment: str = "neutral"  # positive | neutral | negative

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


@dataclass
class GoogleReview:
    """A single Google review for the target company."""
    id: str
    author: str
    rating: int  # 1-5 stars
    text: str
    timestamp: str
    helpful_count: int = 0
    sentiment: str = "neutral"

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


@dataclass
class FeedSnapshot:
    """A point-in-time snapshot of all feeds for a company."""
    company: str
    fetched_at: str
    tweets: list[Tweet] = field(default_factory=list)
    reviews: list[GoogleReview] = field(default_factory=list)
    tweet_count: int = 0
    review_count: int = 0
    avg_review_rating: float = 0.0
    sentiment_summary: dict[str, int] = field(default_factory=dict)

    def to_dict(self) -> dict[str, Any]:
        return {
            "company": self.company,
            "fetched_at": self.fetched_at,
            "tweets": [t.to_dict() for t in self.tweets],
            "reviews": [r.to_dict() for r in self.reviews],
            "tweet_count": self.tweet_count,
            "review_count": self.review_count,
            "avg_review_rating": self.avg_review_rating,
            "sentiment_summary": self.sentiment_summary,
        }


@dataclass
class DailyReport:
    """Daily market analysis report generated by the heartbeat."""
    company: str
    report_date: str
    generated_at: str
    tweet_summary: dict[str, Any] = field(default_factory=dict)
    review_summary: dict[str, Any] = field(default_factory=dict)
    sentiment_trend: str = ""
    key_themes: list[str] = field(default_factory=list)
    action_items: list[str] = field(default_factory=list)
    market_pulse: str = ""

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


# ---------------------------------------------------------------------------
# Demo data for Accelerate Okanagan
# ---------------------------------------------------------------------------

def _generate_demo_tweets() -> list[Tweet]:
    """Generate realistic demo tweets about Accelerate Okanagan."""
    now = datetime.utcnow()
    tweets = [
        Tweet(
            id="tw_001",
            author="Sarah Chen",
            handle="@sarahchentech",
            content="Just finished the @AccelerateOK startup bootcamp - the mentorship sessions were incredible. Connected with 3 potential investors in one afternoon! #OkanaganTech #StartupLife",
            timestamp=(now - timedelta(hours=2)).isoformat(),
            likes=45, retweets=12, replies=8,
            sentiment="positive",
        ),
        Tweet(
            id="tw_002",
            author="Mike Rodriguez",
            handle="@mikerodriguezBC",
            content="Accelerate Okanagan's new coworking space is a game changer for remote founders. Finally a proper tech hub in Kelowna. @AccelerateOK",
            timestamp=(now - timedelta(hours=5)).isoformat(),
            likes=67, retweets=23, replies=15,
            sentiment="positive",
        ),
        Tweet(
            id="tw_003",
            author="TechBC Weekly",
            handle="@techbcweekly",
            content="Report: Okanagan tech sector grew 18% in 2025, with @AccelerateOK-supported startups accounting for $42M in new revenue. Full analysis: [link]",
            timestamp=(now - timedelta(hours=8)).isoformat(),
            likes=134, retweets=56, replies=22,
            sentiment="positive",
        ),
        Tweet(
            id="tw_004",
            author="Jordan Park",
            handle="@jordanpark_dev",
            content="Applied to the @AccelerateOK Venture program 3 months ago, still waiting to hear back. The application process could use some improvement tbh.",
            timestamp=(now - timedelta(hours=12)).isoformat(),
            likes=8, retweets=1, replies=3,
            sentiment="negative",
        ),
        Tweet(
            id="tw_005",
            author="Kelowna Chamber",
            handle="@KelownaChamber",
            content="Proud to partner with @AccelerateOK on the 2026 Innovation Awards. Nominations are open for tech companies making an impact in the Okanagan region.",
            timestamp=(now - timedelta(hours=18)).isoformat(),
            likes=89, retweets=34, replies=11,
            sentiment="positive",
        ),
        Tweet(
            id="tw_006",
            author="Emily Tran",
            handle="@emilytran_ux",
            content="The @AccelerateOK pitch night was fine but I wish they had more diversity in the judging panel. Only 1 woman out of 5 judges? We can do better. #DiversityInTech",
            timestamp=(now - timedelta(hours=24)).isoformat(),
            likes=52, retweets=18, replies=27,
            sentiment="negative",
        ),
        Tweet(
            id="tw_007",
            author="DataFlow Systems",
            handle="@dataflowsys",
            content="Excited to announce we just graduated from @AccelerateOK's acceleration program! Raised our seed round and hiring 5 engineers. Thank you to the whole AO team!",
            timestamp=(now - timedelta(hours=30)).isoformat(),
            likes=201, retweets=78, replies=45,
            sentiment="positive",
        ),
        Tweet(
            id="tw_008",
            author="Ben Okafor",
            handle="@benokafor",
            content="Had coffee with the @AccelerateOK team yesterday. Their knowledge of the BC tech ecosystem is unmatched. Good advice on market entry strategy for our SaaS.",
            timestamp=(now - timedelta(hours=36)).isoformat(),
            likes=34, retweets=6, replies=4,
            sentiment="positive",
        ),
        Tweet(
            id="tw_009",
            author="Startup Grind Kelowna",
            handle="@SGKelowna",
            content="Tonight's fireside chat with @AccelerateOK's CEO was standing room only. Key takeaway: the Okanagan is becoming Canada's next major tech corridor. #StartupGrind",
            timestamp=(now - timedelta(hours=42)).isoformat(),
            likes=76, retweets=29, replies=13,
            sentiment="positive",
        ),
        Tweet(
            id="tw_010",
            author="Alex Kim",
            handle="@alexkim_startup",
            content="Is @AccelerateOK still relevant in 2026? With so many online accelerators, I'm wondering if a regional focus is a strength or a limitation. Thoughts? #BCTech",
            timestamp=(now - timedelta(hours=48)).isoformat(),
            likes=23, retweets=5, replies=19,
            sentiment="neutral",
        ),
        Tweet(
            id="tw_011",
            author="Okanagan Innovates",
            handle="@OKInnovates",
            content="Great workshop at @AccelerateOK today on AI adoption for small businesses. The hands-on demos made complex concepts accessible to everyone in the room.",
            timestamp=(now - timedelta(hours=52)).isoformat(),
            likes=41, retweets=14, replies=6,
            sentiment="positive",
        ),
        Tweet(
            id="tw_012",
            author="Priya Sharma",
            handle="@priyasharma_pm",
            content="@AccelerateOK's mentorship matching could be better. Got paired with someone outside my industry. Feedback submitted, hoping they iterate on this.",
            timestamp=(now - timedelta(hours=60)).isoformat(),
            likes=11, retweets=2, replies=7,
            sentiment="negative",
        ),
    ]
    return tweets


def _generate_demo_reviews() -> list[GoogleReview]:
    """Generate realistic Google reviews for Accelerate Okanagan."""
    now = datetime.utcnow()
    reviews = [
        GoogleReview(
            id="gr_001",
            author="Marcus W.",
            rating=5,
            text="Accelerate Okanagan completely changed the trajectory of our startup. The mentors are experienced, the network is invaluable, and the programs are well-structured. Can't recommend enough for any tech founder in BC.",
            timestamp=(now - timedelta(days=3)).isoformat(),
            helpful_count=14,
            sentiment="positive",
        ),
        GoogleReview(
            id="gr_002",
            author="Lisa Park",
            rating=4,
            text="Good resources and networking events. The coworking space is modern and well-maintained. Only giving 4 stars because some of the programming feels geared toward later-stage companies. More support for idea-stage founders would be great.",
            timestamp=(now - timedelta(days=7)).isoformat(),
            helpful_count=9,
            sentiment="positive",
        ),
        GoogleReview(
            id="gr_003",
            author="David Chen",
            rating=5,
            text="The venture acceleration program was exactly what we needed. Helped us refine our pitch, connected us with angel investors, and their demo day had real decision-makers in the audience. Raised $500K within 2 months of graduating.",
            timestamp=(now - timedelta(days=12)).isoformat(),
            helpful_count=22,
            sentiment="positive",
        ),
        GoogleReview(
            id="gr_004",
            author="Amara Johnson",
            rating=3,
            text="Mixed experience. The events and workshops are excellent, but the actual acceleration program felt a bit generic. I was hoping for more tailored advice for our specific market (agtech). Still, the community alone makes it worthwhile.",
            timestamp=(now - timedelta(days=18)).isoformat(),
            helpful_count=7,
            sentiment="neutral",
        ),
        GoogleReview(
            id="gr_005",
            author="Ryan Foster",
            rating=5,
            text="As a solo founder, AO gave me the support system I desperately needed. Weekly check-ins with my mentor, access to legal and accounting resources, and a community of founders who actually understand the grind. 10/10.",
            timestamp=(now - timedelta(days=22)).isoformat(),
            helpful_count=18,
            sentiment="positive",
        ),
        GoogleReview(
            id="gr_006",
            author="Nina Kowalski",
            rating=2,
            text="Applied twice and was rejected both times without meaningful feedback. The application process feels like a black box. Would appreciate more transparency about what they're looking for in startups.",
            timestamp=(now - timedelta(days=28)).isoformat(),
            helpful_count=11,
            sentiment="negative",
        ),
        GoogleReview(
            id="gr_007",
            author="James Liu",
            rating=4,
            text="Great organization doing important work for the Okanagan tech ecosystem. Their events bring together founders, investors, and corporate partners effectively. The new downtown space is impressive.",
            timestamp=(now - timedelta(days=35)).isoformat(),
            helpful_count=6,
            sentiment="positive",
        ),
        GoogleReview(
            id="gr_008",
            author="Tanya Redbird",
            rating=5,
            text="Accelerate Okanagan helped our Indigenous-led tech company navigate the startup world. The team was respectful, knowledgeable, and genuinely invested in our success. They're building something special in Kelowna.",
            timestamp=(now - timedelta(days=40)).isoformat(),
            helpful_count=31,
            sentiment="positive",
        ),
        GoogleReview(
            id="gr_009",
            author="Carlos Mendez",
            rating=4,
            text="Solid accelerator program with good connections in the BC tech scene. The workshops on product-market fit and go-to-market strategy were particularly useful. Would love to see more focus on international expansion.",
            timestamp=(now - timedelta(days=45)).isoformat(),
            helpful_count=5,
            sentiment="positive",
        ),
        GoogleReview(
            id="gr_010",
            author="Hannah Wright",
            rating=3,
            text="The networking events are the real value here. Met my co-founder at an AO mixer. The formal programs are decent but not groundbreaking compared to what you can find online. Location is convenient though.",
            timestamp=(now - timedelta(days=50)).isoformat(),
            helpful_count=8,
            sentiment="neutral",
        ),
    ]
    return reviews


# ---------------------------------------------------------------------------
# Sentiment analysis (rule-based for demo; LLM would handle this in prod)
# ---------------------------------------------------------------------------

POSITIVE_WORDS = {
    "great", "excellent", "amazing", "incredible", "love", "best", "fantastic",
    "wonderful", "perfect", "outstanding", "recommended", "impressed", "valuable",
    "helpful", "game changer", "excited", "proud", "invaluable", "success",
    "changed", "special", "invested", "raised", "grew", "hiring",
}

NEGATIVE_WORDS = {
    "bad", "terrible", "awful", "poor", "worst", "disappointed", "frustrated",
    "waste", "rejected", "black box", "limitation", "generic", "waiting",
    "improvement", "better", "could be", "wish", "unfortunately",
}


def _classify_sentiment(text: str) -> str:
    """Simple keyword-based sentiment classification."""
    lower = text.lower()
    pos = sum(1 for w in POSITIVE_WORDS if w in lower)
    neg = sum(1 for w in NEGATIVE_WORDS if w in lower)
    if pos > neg:
        return "positive"
    elif neg > pos:
        return "negative"
    return "neutral"


# ---------------------------------------------------------------------------
# Social Feed Monitor
# ---------------------------------------------------------------------------

class SocialFeedMonitor:
    """
    Monitors Twitter and Google Reviews for a target company.

    Stores feed data in JSON files that are accessible to the agent for
    analysis. Provides a heartbeat scheduler that generates daily reports.

    Usage:
        monitor = SocialFeedMonitor("Accelerate Okanagan")
        snapshot = await monitor.fetch_feeds()
        report = monitor.generate_report()
        monitor.start_heartbeat(interval_seconds=86400)  # daily
    """

    def __init__(self, company: str = "Accelerate Okanagan"):
        self.company = company
        self._heartbeat_task: Optional[asyncio.Task] = None
        self._heartbeat_running = False
        self._ensure_storage()

    def _ensure_storage(self) -> None:
        """Create storage directories if they don't exist."""
        FEEDS_DIR.mkdir(parents=True, exist_ok=True)
        REPORTS_DIR.mkdir(parents=True, exist_ok=True)

    # -- Feed fetching -------------------------------------------------------

    async def fetch_feeds(self) -> FeedSnapshot:
        """
        Fetch latest tweets and reviews for the target company.

        In production, this calls the Twitter API and Google Places API.
        For the demo, it returns realistic sample data.
        """
        logger.info("Fetching social feeds for %s", self.company)

        tweets = _generate_demo_tweets()
        reviews = _generate_demo_reviews()

        # Build snapshot
        all_sentiments = (
            [t.sentiment for t in tweets] + [r.sentiment for r in reviews]
        )
        sentiment_counts = {
            "positive": sum(1 for s in all_sentiments if s == "positive"),
            "negative": sum(1 for s in all_sentiments if s == "negative"),
            "neutral": sum(1 for s in all_sentiments if s == "neutral"),
        }

        avg_rating = (
            sum(r.rating for r in reviews) / len(reviews) if reviews else 0.0
        )

        snapshot = FeedSnapshot(
            company=self.company,
            fetched_at=datetime.utcnow().isoformat(),
            tweets=tweets,
            reviews=reviews,
            tweet_count=len(tweets),
            review_count=len(reviews),
            avg_review_rating=round(avg_rating, 2),
            sentiment_summary=sentiment_counts,
        )

        # Persist to JSON
        self._save_feeds(snapshot)
        logger.info(
            "Fetched %d tweets and %d reviews for %s",
            len(tweets), len(reviews), self.company,
        )
        return snapshot

    def _save_feeds(self, snapshot: FeedSnapshot) -> None:
        """Save feed data to JSON files."""
        TWITTER_FILE.write_text(json.dumps(
            {"company": self.company, "tweets": [t.to_dict() for t in snapshot.tweets]},
            indent=2,
        ))
        REVIEWS_FILE.write_text(json.dumps(
            {"company": self.company, "reviews": [r.to_dict() for r in snapshot.reviews]},
            indent=2,
        ))
        logger.info("Feed data saved to %s", FEEDS_DIR)

    def load_feeds(self) -> FeedSnapshot:
        """Load the most recently saved feed data from disk."""
        tweets = []
        reviews = []

        if TWITTER_FILE.exists():
            data = json.loads(TWITTER_FILE.read_text())
            tweets = [Tweet(**t) for t in data.get("tweets", [])]

        if REVIEWS_FILE.exists():
            data = json.loads(REVIEWS_FILE.read_text())
            reviews = [GoogleReview(**r) for r in data.get("reviews", [])]

        all_sentiments = (
            [t.sentiment for t in tweets] + [r.sentiment for r in reviews]
        )
        sentiment_counts = {
            "positive": sum(1 for s in all_sentiments if s == "positive"),
            "negative": sum(1 for s in all_sentiments if s == "negative"),
            "neutral": sum(1 for s in all_sentiments if s == "neutral"),
        }
        avg_rating = (
            sum(r.rating for r in reviews) / len(reviews) if reviews else 0.0
        )

        return FeedSnapshot(
            company=self.company,
            fetched_at=datetime.utcnow().isoformat(),
            tweets=tweets,
            reviews=reviews,
            tweet_count=len(tweets),
            review_count=len(reviews),
            avg_review_rating=round(avg_rating, 2),
            sentiment_summary=sentiment_counts,
        )

    # -- Report generation ---------------------------------------------------

    def generate_report(self, snapshot: Optional[FeedSnapshot] = None) -> DailyReport:
        """
        Generate a daily market analysis report from the current feed data.

        This is the kind of report the heartbeat function produces each day:
        sentiment trends, key themes, and action items a business owner can
        act on immediately.
        """
        if snapshot is None:
            snapshot = self.load_feeds()

        now = datetime.utcnow()

        # Tweet analysis
        tweet_engagement = sum(
            t.likes + t.retweets + t.replies for t in snapshot.tweets
        )
        top_tweet = max(
            snapshot.tweets,
            key=lambda t: t.likes + t.retweets + t.replies,
            default=None,
        )
        tweet_sentiments = [t.sentiment for t in snapshot.tweets]

        tweet_summary = {
            "total_tweets": len(snapshot.tweets),
            "total_engagement": tweet_engagement,
            "avg_engagement": round(tweet_engagement / max(len(snapshot.tweets), 1), 1),
            "sentiment_breakdown": {
                "positive": tweet_sentiments.count("positive"),
                "neutral": tweet_sentiments.count("neutral"),
                "negative": tweet_sentiments.count("negative"),
            },
            "top_tweet": top_tweet.to_dict() if top_tweet else None,
        }

        # Review analysis
        ratings = [r.rating for r in snapshot.reviews]
        review_sentiments = [r.sentiment for r in snapshot.reviews]

        review_summary = {
            "total_reviews": len(snapshot.reviews),
            "average_rating": round(sum(ratings) / max(len(ratings), 1), 2),
            "rating_distribution": {
                str(i): ratings.count(i) for i in range(1, 6)
            },
            "sentiment_breakdown": {
                "positive": review_sentiments.count("positive"),
                "neutral": review_sentiments.count("neutral"),
                "negative": review_sentiments.count("negative"),
            },
        }

        # Overall sentiment trend
        total_positive = (
            tweet_sentiments.count("positive") + review_sentiments.count("positive")
        )
        total_negative = (
            tweet_sentiments.count("negative") + review_sentiments.count("negative")
        )
        total = len(tweet_sentiments) + len(review_sentiments)

        if total > 0:
            pos_pct = round(total_positive / total * 100)
            neg_pct = round(total_negative / total * 100)
            if pos_pct >= 70:
                sentiment_trend = f"Very Positive ({pos_pct}% positive mentions)"
            elif pos_pct >= 50:
                sentiment_trend = f"Mostly Positive ({pos_pct}% positive, {neg_pct}% negative)"
            elif neg_pct >= 50:
                sentiment_trend = f"Concerning ({neg_pct}% negative mentions - needs attention)"
            else:
                sentiment_trend = f"Mixed ({pos_pct}% positive, {neg_pct}% negative)"
        else:
            sentiment_trend = "No data available"

        # Extract key themes from content
        key_themes = self._extract_themes(snapshot)

        # Generate action items
        action_items = self._generate_action_items(snapshot, tweet_summary, review_summary)

        # Market pulse - executive summary
        market_pulse = self._generate_market_pulse(snapshot, sentiment_trend)

        report = DailyReport(
            company=self.company,
            report_date=now.strftime("%Y-%m-%d"),
            generated_at=now.isoformat(),
            tweet_summary=tweet_summary,
            review_summary=review_summary,
            sentiment_trend=sentiment_trend,
            key_themes=key_themes,
            action_items=action_items,
            market_pulse=market_pulse,
        )

        # Save report
        self._save_report(report)
        return report

    def _extract_themes(self, snapshot: FeedSnapshot) -> list[str]:
        """Extract recurring themes from tweets and reviews."""
        themes = []

        # Look for common topics
        all_text = " ".join(
            [t.content for t in snapshot.tweets] +
            [r.text for r in snapshot.reviews]
        ).lower()

        theme_keywords = {
            "Mentorship & Support": ["mentor", "support", "guidance", "advice", "check-in"],
            "Networking & Community": ["network", "community", "connect", "partner", "mixer"],
            "Startup Programs": ["program", "accelerat", "bootcamp", "venture", "demo day"],
            "Coworking & Facilities": ["space", "coworking", "office", "downtown", "facility"],
            "Funding & Investment": ["invest", "raised", "seed", "angel", "funding", "revenue"],
            "Diversity & Inclusion": ["diversity", "inclusion", "indigenous", "women", "underrepresented"],
            "Tech Ecosystem Growth": ["ecosystem", "grew", "growth", "corridor", "sector"],
            "Application Process": ["application", "applied", "rejected", "process", "feedback"],
        }

        for theme, keywords in theme_keywords.items():
            hits = sum(1 for kw in keywords if kw in all_text)
            if hits >= 2:
                themes.append(theme)

        return themes[:6]  # Top 6 themes

    def _generate_action_items(
        self,
        snapshot: FeedSnapshot,
        tweet_summary: dict,
        review_summary: dict,
    ) -> list[str]:
        """Generate actionable recommendations for the business owner."""
        items = []

        # Check for negative sentiment spikes
        neg_tweets = tweet_summary["sentiment_breakdown"]["negative"]
        if neg_tweets >= 3:
            items.append(
                f"ATTENTION: {neg_tweets} negative tweets detected. Review and consider "
                "responding to address concerns publicly."
            )

        # Check review ratings
        avg_rating = review_summary["average_rating"]
        if avg_rating < 4.0:
            items.append(
                f"Average Google rating is {avg_rating}/5. Identify common complaints "
                "and develop an improvement plan."
            )

        # High engagement opportunities
        top = tweet_summary.get("top_tweet")
        if top and (top["likes"] + top["retweets"]) > 100:
            items.append(
                "A tweet about your organization went viral (100+ engagements). "
                "Consider amplifying this content and engaging with the conversation."
            )

        # Application process feedback
        neg_reviews = [r for r in snapshot.reviews if r.sentiment == "negative"]
        if neg_reviews:
            items.append(
                f"{len(neg_reviews)} negative review(s) detected. Consider reaching out "
                "to these reviewers to address their concerns and show responsiveness."
            )

        # Community engagement
        items.append(
            "Engage with positive mentions by liking, retweeting, and thanking supporters. "
            "This strengthens community relationships and boosts visibility."
        )

        return items

    def _generate_market_pulse(self, snapshot: FeedSnapshot, sentiment_trend: str) -> str:
        """Generate an executive summary paragraph."""
        tweet_count = snapshot.tweet_count
        review_count = snapshot.review_count
        avg_rating = snapshot.avg_review_rating

        return (
            f"**Market Pulse for {self.company}** ({datetime.utcnow().strftime('%B %d, %Y')})\n\n"
            f"Over the monitoring period, {tweet_count} tweets and {review_count} Google reviews "
            f"were tracked. The overall sentiment is **{sentiment_trend.lower()}**. "
            f"Google Reviews average **{avg_rating}/5 stars**.\n\n"
            f"The Okanagan tech community is actively discussing {self.company}'s programs, "
            f"with the strongest positive signals around mentorship quality, networking events, "
            f"and ecosystem growth. Areas flagged for improvement include application transparency "
            f"and diversity in leadership panels.\n\n"
            f"**Recommendation:** Focus engagement efforts on amplifying positive stories "
            f"from program graduates while proactively addressing process feedback."
        )

    def _save_report(self, report: DailyReport) -> Path:
        """Save a daily report to disk."""
        filename = f"daily_report_{report.report_date}.json"
        path = REPORTS_DIR / filename
        path.write_text(json.dumps(report.to_dict(), indent=2))
        logger.info("Daily report saved to %s", path)
        return path

    def list_reports(self) -> list[dict[str, str]]:
        """List all saved daily reports."""
        if not REPORTS_DIR.exists():
            return []
        reports = []
        for p in sorted(REPORTS_DIR.glob("daily_report_*.json"), reverse=True):
            reports.append({
                "filename": p.name,
                "path": str(p),
                "date": p.stem.replace("daily_report_", ""),
                "modified": datetime.fromtimestamp(p.stat().st_mtime).isoformat(),
            })
        return reports

    def load_report(self, path: str) -> dict[str, Any]:
        """Load a saved report from disk."""
        return json.loads(Path(path).read_text())

    # -- Heartbeat scheduler -------------------------------------------------

    def start_heartbeat(self, interval_seconds: int = 86400) -> bool:
        """
        Start the heartbeat scheduler that periodically fetches feeds
        and generates reports.

        Args:
            interval_seconds: How often to run (default: 86400 = 24 hours)

        Returns:
            True if started, False if already running
        """
        if self._heartbeat_running:
            logger.warning("Heartbeat already running")
            return False

        self._heartbeat_running = True
        self._heartbeat_task = asyncio.create_task(
            self._heartbeat_loop(interval_seconds)
        )
        logger.info(
            "Heartbeat started for %s (interval: %ds)",
            self.company, interval_seconds,
        )
        return True

    def stop_heartbeat(self) -> bool:
        """Stop the heartbeat scheduler."""
        if not self._heartbeat_running:
            return False

        self._heartbeat_running = False
        if self._heartbeat_task:
            self._heartbeat_task.cancel()
            self._heartbeat_task = None
        logger.info("Heartbeat stopped for %s", self.company)
        return True

    @property
    def heartbeat_active(self) -> bool:
        return self._heartbeat_running

    async def _heartbeat_loop(self, interval: int) -> None:
        """Internal heartbeat loop that fetches and reports on schedule."""
        try:
            while self._heartbeat_running:
                logger.info("Heartbeat tick: fetching feeds for %s", self.company)
                try:
                    snapshot = await self.fetch_feeds()
                    report = self.generate_report(snapshot)
                    logger.info(
                        "Heartbeat report generated: %s (sentiment: %s)",
                        report.report_date, report.sentiment_trend,
                    )
                except Exception as exc:
                    logger.error("Heartbeat fetch/report failed: %s", exc)

                await asyncio.sleep(interval)
        except asyncio.CancelledError:
            logger.info("Heartbeat loop cancelled")

    # -- Chat handler --------------------------------------------------------

    async def handle_chat(self, message: str, context: dict) -> str:
        """Handle social feed requests from the chat interface."""
        lower = message.lower()

        if "fetch" in lower or "refresh" in lower or "update" in lower:
            snapshot = await self.fetch_feeds()
            return self._format_snapshot_text(snapshot)

        if "report" in lower or "analysis" in lower or "summary" in lower:
            snapshot = await self.fetch_feeds()
            report = self.generate_report(snapshot)
            return self._format_report_text(report)

        if "heartbeat" in lower and ("start" in lower or "enable" in lower):
            started = self.start_heartbeat()
            if started:
                return (
                    f"Heartbeat monitoring started for **{self.company}**.\n\n"
                    "I will automatically fetch social feeds and generate a daily "
                    "market analysis report every 24 hours. You can check the latest "
                    "report anytime by asking me for it."
                )
            return "Heartbeat is already running."

        if "heartbeat" in lower and ("stop" in lower or "disable" in lower):
            stopped = self.stop_heartbeat()
            if stopped:
                return f"Heartbeat monitoring stopped for **{self.company}**."
            return "Heartbeat is not currently running."

        # Default: show overview and options
        snapshot = await self.fetch_feeds()
        return self._format_feed_overview(snapshot)

    def _format_feed_overview(self, snapshot: FeedSnapshot) -> str:
        """Format a brief overview of the social feeds."""
        return (
            f"## Social Feed Monitor - {self.company}\n\n"
            f"**Twitter/X:** {snapshot.tweet_count} recent tweets tracked\n"
            f"**Google Reviews:** {snapshot.review_count} reviews ({snapshot.avg_review_rating}/5 avg)\n"
            f"**Overall Sentiment:** {snapshot.sentiment_summary}\n\n"
            "**What would you like to do?**\n"
            "- Say **\"show report\"** for a full daily market analysis\n"
            "- Say **\"refresh feeds\"** to fetch the latest data\n"
            "- Say **\"start heartbeat\"** to enable daily automated monitoring\n"
            "- Say **\"stop heartbeat\"** to disable automated monitoring\n\n"
            f"Heartbeat status: {'Active' if self.heartbeat_active else 'Inactive'}"
        )

    def _format_snapshot_text(self, snapshot: FeedSnapshot) -> str:
        """Format a feed snapshot for display in chat."""
        lines = [
            f"## Social Feeds - {self.company}",
            f"*Fetched at {snapshot.fetched_at}*\n",
            f"### Twitter/X ({snapshot.tweet_count} tweets)",
            "",
        ]
        for t in snapshot.tweets[:5]:
            lines.append(f"**{t.author}** ({t.handle}) - {t.sentiment.upper()}")
            lines.append(f"> {t.content}")
            lines.append(f"  Likes: {t.likes} | RT: {t.retweets} | Replies: {t.replies}\n")

        if snapshot.tweet_count > 5:
            lines.append(f"*...and {snapshot.tweet_count - 5} more tweets*\n")

        lines.append(f"### Google Reviews ({snapshot.review_count} reviews, avg {snapshot.avg_review_rating}/5)")
        lines.append("")
        for r in snapshot.reviews[:5]:
            stars = "★" * r.rating + "☆" * (5 - r.rating)
            lines.append(f"**{r.author}** {stars} - {r.sentiment.upper()}")
            lines.append(f"> {r.text[:200]}{'...' if len(r.text) > 200 else ''}\n")

        if snapshot.review_count > 5:
            lines.append(f"*...and {snapshot.review_count - 5} more reviews*\n")

        lines.append("---")
        lines.append(f"**Sentiment Summary:** {snapshot.sentiment_summary}")
        return "\n".join(lines)

    def _format_report_text(self, report: DailyReport) -> str:
        """Format a daily report for display in chat."""
        lines = [
            f"## Daily Market Analysis - {report.company}",
            f"*{report.report_date}*\n",
            report.market_pulse,
            "",
            "### Twitter Activity",
            f"- **{report.tweet_summary['total_tweets']}** tweets tracked",
            f"- **{report.tweet_summary['total_engagement']}** total engagements",
            f"- Avg engagement per tweet: **{report.tweet_summary['avg_engagement']}**",
            f"- Sentiment: {report.tweet_summary['sentiment_breakdown']}",
            "",
            "### Google Reviews",
            f"- **{report.review_summary['total_reviews']}** reviews",
            f"- Average rating: **{report.review_summary['average_rating']}/5**",
            f"- Rating distribution: {report.review_summary['rating_distribution']}",
            f"- Sentiment: {report.review_summary['sentiment_breakdown']}",
            "",
            f"### Sentiment Trend: {report.sentiment_trend}",
            "",
        ]

        if report.key_themes:
            lines.append("### Key Themes")
            for theme in report.key_themes:
                lines.append(f"- {theme}")
            lines.append("")

        if report.action_items:
            lines.append("### Action Items")
            for i, item in enumerate(report.action_items, 1):
                lines.append(f"{i}. {item}")

        return "\n".join(lines)
